import { Button, Center } from '@chakra-ui/react';
import { type NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Center h="100vh">
          <Button>Touch Me</Button>
        </Center>
      </div>
    </>
  );
};

export default Home;
